### Retrieve Users
GET https://cse341-project2-a80q.onrender.com/users/
Content-Type: application/json

### Add a New User
POST https://cse341-project2-a80q.onrender.com/users/
Content-Type: application/json

{
  "userId": 1,
  "name": "John Doe",
  "email": "johndoe@example.com",
  "languagesLearning": ["English", "Spanish"],
  "completedLessons": [1, 2, 3],
  "points": 100
}


### Retrieve User by ID
GET https://cse341-project2-a80q.onrender.com/users/{userId}
Content-Type: application/json

### Modify a User
PUT https://cse341-project2-a80q.onrender.com/users/{userId}
Content-Type: application/json

{
    "userId": "any",
    "name": "any",
    "email": "any",
    "languagesLearning": "any",
    "completedLessons": "any",
    "points": "any"
}

### Delete a User
DELETE https://cse341-project2-a80q.onrender.com/users/6731c5636f6926b868a01dcf
Content-Type: application/json
